services:
  - type: web
    name: backend
    env: node
    region: oregon # Choose the appropriate region for your app
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://immilankumar01:thedash@cluster0.3kddd.mongodb.net/tutor?retryWrites=true
      - key: JWT_SECRET
        value: your_jwt_secret
